let dataNavbar = [
  { title: "Browse", content: ["Primo", "Secondo", "Terzo", "Quarto"] },
  { title: "Landings", content: ["Primo", "Secondo", "Terzo", "Quarto"] },
  { title: "Pages", content: ["Primo", "Secondo", "Terzo", "Quarto"] },
  { title: "Accounts", content: ["Primo", "Secondo", "Terzo", "Quarto"] },
];

let dataCards = [
  {
    img: "./assets/course-graphql.jpg",
    txtCard: "GraphQL: introduction to graphQL for beginners",
    time: "2h 40m",
    complex: 4,
    complexTx: "Advance",
    star: 2.5,
    feedback: "(1,500)",
    priceFinal: "$500",
    priceOriginal: "$600",
    nameTeacher: "Brooklyn Simmons",
    imgTeacher: "./assets/avatar-5.jpg",
  },
  {
    img: "./assets/course-javascript.jpg",
    txtCard: "A Complete Beginner's Guide to JavaScript",
    time: "4h 10m",
    complex: 4,
    complexTx: "Advance",
    star: 3.5,
    feedback: "(7,500)",
    priceFinal: "$700",
    priceOriginal: "$850",
    nameTeacher: "Jenny Wilson",
    imgTeacher: "./assets/avatar-1.jpg",
  },
  {
    img: "./assets/course-node.jpg",
    txtCard: "Beginning Node.js, Express & MongoDB Development",
    time: "2h 00m",
    complex: 3,
    complexTx: "Intermediate",
    star: 4.0,
    feedback: "(15,700)",
    priceFinal: "$800",
    priceOriginal: "$950",
    nameTeacher: "Sina Ray",
    imgTeacher: "./assets/avatar-3.jpg",
  },
  {
    img: "./assets/course-laravel.jpg",
    txtCard: "Laravel: The Ultimate Beginner's Guide to Learn",
    time: "1h 00m",
    complex: 1,
    complexTx: "Beginner",
    star: 4.5,
    feedback: "(2,500)",
    priceFinal: "$170",
    priceOriginal: "$220",
    nameTeacher: "Sobo Rikhan",
    imgTeacher: "./assets/avatar-7.jpg",
  },
  {
    img: "./assets/course-html.jpg",
    txtCard: "HTML Full Course - Build a Website Tutorial",
    time: "3h 16m",
    complex: 1,
    complexTx: "Beginner",
    star: 3,
    feedback: "(1,600)",
    priceFinal: "$550",
    priceOriginal: "$700",
    nameTeacher: "Miston Wilson",
    imgTeacher: "./assets/avatar-4.jpg",
  },
  {
    img: "./assets/course-react.jpg",
    txtCard: "How to easily create a website with React",
    time: "3h 55m",
    complex: 4,
    complexTx: "Advance",
    star: 4.5,
    feedback: "(1,500)",
    priceFinal: "$600",
    priceOriginal: "$750",
    nameTeacher: "April Noms",
    imgTeacher: "./assets/avatar-2.jpg",
  },
  {
    img: "./assets/course-gatsby.jpg",
    txtCard: "Revolutionize how you build the web",
    time: "1h 46m",
    complex: 2,
    complexTx: "Intermediate",
    star: 2.0,
    feedback: "(16,500)",
    priceFinal: "$800",
    priceOriginal: "$850",
    nameTeacher: "Jenny Wilson",
    imgTeacher: "./assets/avatar-1.jpg",
  },
  {
    img: "./assets/course-node.jpg",
    txtCard: "Beginning Node.js, Express & MongoDB Development",
    time: "2h 00m",
    complex: 3,
    complexTx: "Intermediate",
    star: 4.0,
    feedback: "(15,700)",
    priceFinal: "$800",
    priceOriginal: "$950",
    nameTeacher: "Sina Ray",
    imgTeacher: "./assets/avatar-3.jpg",
  },
];
